services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: insider_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - insider
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: insider_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - insider
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: insider_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: insider_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: insider_pass
      MYSQL_USER: insider_user
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - insider

  redis:
    image: redis:7-alpine
    container_name: insider_redis
    restart: unless-stopped
    ports:
      - "63790:6379"
    networks:
      - insider

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: insider_queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./:/var/www
    networks:
      - insider
    depends_on:
      - app
      - db
      - redis

networks:
  insider:
    driver: bridge

volumes:
  dbdata:
    driver: local

